services:
  # Backend API Service
  - type: web
    name: feedback-backend
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: feedback-frontend
    env: static
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /admin
        destination: /admin-dashboard.html
      - type: rewrite
        source: /admin-dashboard.html
        destination: /admin-dashboard.html
