services:
  # Backend API Service
  - type: web
    name: feedback-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: feedback-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: "npm ci || npm i && npm run build"
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /admin
        destination: /admin-dashboard.html
      - type: rewrite
        source: /admin-dashboard.html
        destination: /admin-dashboard.html
